# Generated by Django 3.1.5 on 2021-01-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='grade',
        ),
        migrations.DeleteModel(
            name='note',
        ),
        migrations.DeleteModel(
            name='notice',
        ),
        migrations.DeleteModel(
            name='table',
        ),
    ]
