# Generated by Django 3.1.5 on 2021-01-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_auto_20210120_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='subject',
        ),
    ]
