# Generated by Django 3.1.5 on 2021-01-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='fac',
        ),
        migrations.RemoveField(
            model_name='note',
            name='sem',
        ),
        migrations.DeleteModel(
            name='faculty',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='semester',
        ),
    ]
