# Generated by Django 3.1.5 on 2021-01-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_faculty_note_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
