# Generated by Django 3.1.5 on 2021-01-21 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20210121_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='sem',
            new_name='grade',
        ),
    ]
