# Generated by Django 3.1.5 on 2021-01-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20210123_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='fac',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='sem',
            new_name='semester',
        ),
    ]
