# Generated by Django 3.1.5 on 2021-01-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20210121_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='grade',
            new_name='semester',
        ),
    ]
