# Generated by Django 3.1.5 on 2021-01-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20210123_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='faculty',
            field=models.CharField(choices=[('Second', 'Second'), ('Fourth', 'Fourth'), ('Sixth', 'Sixth'), ('Fifth', 'Fifth'), ('First', 'First'), ('Seventh', 'Seventh'), ('Eighth', 'Eighth'), ('Third', 'Third')], max_length=200),
        ),
    ]
