# Generated by Django 3.1.5 on 2021-01-24 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20210124_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.faculty'),
        ),
        migrations.AlterField(
            model_name='note',
            name='semester',
            field=models.CharField(choices=[('Third', 'Third'), ('First', 'First'), ('Seventh', 'Seventh'), ('Eighth', 'Eighth'), ('Sixth', 'Sixth'), ('Fourth', 'Fourth'), ('Second', 'Second'), ('Fifth', 'Fifth')], max_length=200),
        ),
        migrations.DeleteModel(
            name='semester',
        ),
    ]
