# Generated by Django 3.1.5 on 2021-01-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20210124_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='semester',
            field=models.CharField(choices=[('Seventh', 'Seventh'), ('Third', 'Third'), ('Sixth', 'Sixth'), ('Second', 'Second'), ('Fourth', 'Fourth'), ('First', 'First'), ('Eighth', 'Eighth'), ('Fifth', 'Fifth')], max_length=200),
        ),
    ]
