# Generated by Django 3.1.5 on 2021-01-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20210124_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='semester',
            field=models.CharField(choices=[('Sixth', 'Sixth'), ('Seventh', 'Seventh'), ('Fourth', 'Fourth'), ('Third', 'Third'), ('Fifth', 'Fifth'), ('Second', 'Second'), ('Eighth', 'Eighth'), ('First', 'First')], max_length=200),
        ),
    ]
