# Generated by Django 3.1.5 on 2021-01-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20210124_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='semester',
            field=models.CharField(choices=[('First', 'First'), ('Seventh', 'Seventh'), ('Sixth', 'Sixth'), ('Second', 'Second'), ('Fourth', 'Fourth'), ('Eighth', 'Eighth'), ('Fifth', 'Fifth'), ('Third', 'Third')], max_length=200),
        ),
    ]
