# Generated by Django 3.1.5 on 2021-01-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20210124_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='semester',
            field=models.CharField(choices=[('Sixth', 'Sixth'), ('First', 'First'), ('Fourth', 'Fourth'), ('Third', 'Third'), ('Fifth', 'Fifth'), ('Seventh', 'Seventh'), ('Second', 'Second'), ('Eighth', 'Eighth')], max_length=200),
        ),
    ]
