# Generated by Django 3.1.5 on 2021-01-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenttable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='semester',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
