# Generated by Django 3.1.5 on 2021-01-25 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_auto_20210125_0311'),
        ('studenttable', '0002_table_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='faculty',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='notes.faculty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='semester',
            field=models.CharField(choices=[('3', 'Third'), ('2', 'Second'), ('8', 'Eighth'), ('6', 'Sixth'), ('4', 'Fourth'), ('1', 'First'), ('5', 'Fifth'), ('7', 'Seventh')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
