# Generated by Django 3.1.5 on 2021-01-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenttable', '0002_auto_20210120_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='batch',
            field=models.CharField(blank=True, max_length=85, null=True),
        ),
    ]
