# Generated by Django 3.1.5 on 2021-01-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studenttable', '0003_auto_20210120_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='table',
            name='address2',
        ),
    ]
