# Generated by Django 3.1.5 on 2021-01-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenttable', '0004_auto_20210120_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='table',
            name='address2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
