# Generated by Django 3.1.5 on 2021-01-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to=None)),
                ('date', models.DateField()),
            ],
        ),
    ]
