# Generated by Django 3.1.5 on 2021-01-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
