# Generated by Django 3.1.5 on 2021-01-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20210120_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(),
        ),
    ]
