# Generated by Django 3.1.5 on 2021-01-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20210120_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(),
        ),
    ]
