# Generated by Django 3.1.5 on 2021-01-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0008_auto_20210121_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
    ]
